# Pytorch Basics

In [20]:
import torch
import numpy as np

## Tensors

In [12]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print(f"Values: \n{x}\n")

In [13]:
x = torch.ones((4,3,2)) # Tensors of dimension 4x3x2
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([4, 3, 2])
Values: 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])



In [14]:
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [15]:
describe(torch.rand(2,3)) # uniform distribution
describe(torch.randn(2,3)) # normal distribution

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5579, 0.7634, 0.5017],
        [0.4405, 0.2706, 0.9310]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.6431,  1.2875,  0.0970],
        [-0.4887,  0.0393,  1.3675]])



In [18]:
describe(torch.zeros((2,3))) # zeros tensor
x = torch.ones(2 ,3) # ones tensor
describe(x)
x.fill_(5) # all the function with (_) refers to an in-place operation
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])



In [19]:
x = torch.Tensor([[1, 2, 3],
                 [4, 5, 6]]) # creating a tensor from a list
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [23]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy)) # from numpy to pytorch

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.0272, 0.1653, 0.2550],
        [0.7933, 0.6392, 0.6553]], dtype=torch.float64)



In [29]:
x = torch.rand(2, 3)
describe(x)
x = x.numpy()
print(f"type: {x.dtype}")
print(f"shape: {x.shape}")
print("numpy value: \n{}\n".format(x))


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.2486, 0.9583, 0.9892],
        [0.1774, 0.3104, 0.7007]])

type: float32
shape: (2, 3)
numpy value: 
[[0.2486456  0.9583392  0.98915356]
 [0.17738158 0.3103658  0.70070916]]



## Tensor Types and Size

In [30]:
x = torch.FloatTensor([[1,2,3],
                      [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [31]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [33]:
x = torch.tensor([[1,2,3],
                 [4,5,6]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [42]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [50]:
x.shape, x.size(), x.numel()

(torch.Size([2, 3]), torch.Size([2, 3]), 6)

## Tensor Operations

In [51]:
x = torch.rand(2,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9681, 0.4245, 0.2924],
        [0.6549, 0.9064, 0.3041]])



In [55]:
describe(x.add(x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.9362, 0.8490, 0.5848],
        [1.3099, 1.8127, 0.6081]])



In [53]:
describe(x+x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.9362, 0.8490, 0.5848],
        [1.3099, 1.8127, 0.6081]])



In [56]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])



In [57]:
x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [58]:
x = x.reshape(-1)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])



In [62]:
x = x.view(3, -1)
print(f"original: \n{x}\n")
describe(x.sum(dim=0))

original: 
tensor([[0, 1],
        [2, 3],
        [4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([6, 9])



In [63]:
print(f"original: \n{x}\n")
describe(x.sum(dim=1))

original: 
tensor([[0, 1],
        [2, 3],
        [4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([1, 5, 9])



In [71]:
describe(x.T)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 2, 4],
        [1, 3, 5]])



## Indexing, Slicing and Joining

In [72]:
x = torch.arange(6).view(2, -1)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [73]:
describe(x[:1, :2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])



In [74]:
describe(x[0,1])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1



In [76]:
indices = torch.LongTensor([0, 2])
describe(x.index_select(dim=1, index=indices)) # Getting index 0 and 2 along dim=1

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])



In [81]:
indices = torch.LongTensor([0, 0])
describe(x.index_select(dim=0, index=indices)) # Getting index 0 and 0 along dim=1

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])



In [86]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices]) # Get [0, 1] and [0, 1] (0,0) and (1,1) indices

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])



In [91]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [92]:
describe(torch.cat([x, x], dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])



In [94]:
describe(torch.cat([x, x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])



In [95]:
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])



## Linear Algebra Operators

In [104]:
x1 = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [105]:
x2 = torch.ones(3, 2).long()
x2[:, 1] += 1
describe(x2)

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1, 2],
        [1, 2],
        [1, 2]])



In [106]:
describe(x1.mm(x2))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3,  6],
        [12, 24]])



## Tensors and Computational Graphs

In [119]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print("Grad of x: \n{}".format(x.grad))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

Grad of x: 
None


In [120]:
y = (x + 2) * (x + 5) + 3
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)



In [121]:
z = y.mean()
describe(z)
z.backward()
print("Grad of x: \n{}".format(x.grad))

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0

Grad of x: 
tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])


## GPU

In [123]:
print(torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

False
cpu


# Exercises

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0

In [135]:
x = torch.randn(2,4)
x = x.unsqueeze(0)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([1, 2, 4])
Values: 
tensor([[[-0.7295,  0.2540, -1.5665,  2.1273],
         [ 0.5781,  0.4839,  0.2113,  0.2974]]])



2. Remove the dimension you just added to the previous tensor

In [136]:
x = x.squeeze(0)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values: 
tensor([[-0.7295,  0.2540, -1.5665,  2.1273],
        [ 0.5781,  0.4839,  0.2113,  0.2974]])



In [141]:
torch.squeeze()

tensor([[-0.7295,  0.2540, -1.5665,  2.1273],
        [ 0.5781,  0.4839,  0.2113,  0.2974]])

3. Create a random tensor of shape 5x3 in the interval [3, 7)

In [143]:
x = torch.randint(3, 7, (5, 3))
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[5, 5, 5],
        [4, 5, 6],
        [6, 5, 6],
        [5, 4, 3],
        [4, 6, 5]])



In [151]:
x = 3 + torch.rand(5, 3)*(7-3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[5.8982, 6.6171, 5.5770],
        [6.4726, 6.9522, 3.0201],
        [6.8104, 6.7522, 4.9360],
        [3.1725, 5.8786, 4.9077],
        [6.2401, 6.0239, 5.5634]])



4. Create a tensor with values from a normal distribution 

In [145]:
x = torch.randn((10, ))
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([10])
Values: 
tensor([-2.2908, -0.6397, -0.3174, -0.2031,  0.6639, -0.1302,  1.1424, -1.0429,
        -0.7723,  0.4022])



In [148]:
x = torch.empty(3, 3)
x.normal_()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[-1.2391, -1.3204, -0.2052],
        [-0.9322, -0.9425,  0.3853],
        [ 1.5830, -0.3353, -2.1995]])



5. Retrieve the indexes of all the nonzero elements in the tensor

In [172]:
x = torch.Tensor([1, 1, 1, 0, 3])
x[x.nonzero(as_tuple=True)], x.nonzero(as_tuple=True)

(tensor([1., 1., 1., 3.]), (tensor([0, 1, 2, 4]),))

In [171]:
x[x.nonzero(as_tuple=False)], x.nonzero(as_tuple=False)

(tensor([[1.],
         [1.],
         [1.],
         [3.]]),
 tensor([[0],
         [1],
         [2],
         [4]]))

6. Create a random tensor of size (3,1) and then horizontally stack four copies together.

In [180]:
x = torch.rand(3,1)
describe(x)
describe(torch.cat([x, x, x, x], dim=1))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values: 
tensor([[0.0855],
        [0.2845],
        [0.0492]])

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[0.0855, 0.0855, 0.0855, 0.0855],
        [0.2845, 0.2845, 0.2845, 0.2845],
        [0.0492, 0.0492, 0.0492, 0.0492]])



7. Return the batch matrix-matrix product of two three dimensional matrices

In [185]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
for i in range(a.shape[0]):
    describe(a[i, :, :].mm(b[i, :, :]))

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[2.3330, 1.4652, 1.8560, 2.0571],
        [0.9183, 1.0783, 1.0634, 1.1632],
        [1.6283, 0.7444, 1.4156, 1.4506],
        [1.7620, 0.7040, 1.3555, 1.3380]])

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[0.9123, 1.2952, 0.6912, 1.2785],
        [0.6562, 1.3692, 0.7947, 1.4209],
        [0.9160, 1.9026, 1.0654, 1.3433],
        [0.5931, 1.0163, 1.0302, 1.5411]])

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[1.9929, 0.9974, 0.6811, 1.4151],
        [2.1608, 1.2554, 0.7294, 1.6341],
        [1.3219, 0.6543, 0.3068, 0.7042],
        [0.8816, 0.6026, 0.4747, 0.8350]])



In [187]:
describe(a.bmm(b))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4, 4])
Values: 
tensor([[[2.3330, 1.4652, 1.8560, 2.0571],
         [0.9183, 1.0783, 1.0634, 1.1632],
         [1.6283, 0.7444, 1.4156, 1.4506],
         [1.7620, 0.7040, 1.3555, 1.3380]],

        [[0.9123, 1.2952, 0.6912, 1.2785],
         [0.6562, 1.3692, 0.7947, 1.4209],
         [0.9160, 1.9026, 1.0654, 1.3433],
         [0.5931, 1.0163, 1.0302, 1.5411]],

        [[1.9929, 0.9974, 0.6811, 1.4151],
         [2.1608, 1.2554, 0.7294, 1.6341],
         [1.3219, 0.6543, 0.3068, 0.7042],
         [0.8816, 0.6026, 0.4747, 0.8350]]])



8. Return the batch matrix-matrix product of a 3D matrix and a 2D matrix

In [189]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
for i in range(a.shape[0]):
    describe(a[i, :, :].mm(b))

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[1.6534, 0.9285, 1.3533, 1.9004],
        [1.8780, 1.4682, 1.5658, 2.2391],
        [1.6796, 1.2870, 1.5280, 2.3675],
        [2.0228, 1.3065, 1.5315, 1.9372]])

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[0.6664, 0.9165, 0.6246, 0.9017],
        [1.1912, 1.4743, 1.2247, 1.9942],
        [1.0509, 1.1987, 1.0005, 1.7858],
        [1.6505, 1.4883, 1.5241, 2.2538]])

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[1.1792, 1.1934, 1.1698, 1.8517],
        [1.5317, 1.4082, 1.2555, 1.5253],
        [0.5706, 0.9048, 0.6303, 1.0865],
        [1.5461, 1.3402, 1.4229, 1.9942]])



In [192]:
a.bmm(b.unsqueeze(0).expand(a.shape[0], *b.shape))

tensor([[[1.6534, 0.9285, 1.3533, 1.9004],
         [1.8780, 1.4682, 1.5658, 2.2391],
         [1.6796, 1.2870, 1.5280, 2.3675],
         [2.0228, 1.3065, 1.5315, 1.9372]],

        [[0.6664, 0.9165, 0.6246, 0.9017],
         [1.1912, 1.4743, 1.2247, 1.9942],
         [1.0509, 1.1987, 1.0005, 1.7858],
         [1.6505, 1.4883, 1.5241, 2.2538]],

        [[1.1792, 1.1934, 1.1698, 1.8517],
         [1.5317, 1.4082, 1.2555, 1.5253],
         [0.5706, 0.9048, 0.6303, 1.0865],
         [1.5461, 1.3402, 1.4229, 1.9942]]])

In [208]:
b.unsqueeze(0).expand(a.shape[0], *b.shape) # Repeat matrix to the same batch of a in order to do 
                                            # batch multiplication matrix

tensor([[[0.1062, 0.2419, 0.3641, 0.9233],
         [0.8551, 0.8739, 0.6573, 0.8063],
         [0.8426, 0.2101, 0.5946, 0.4708],
         [0.7164, 0.2004, 0.5117, 0.9060],
         [0.2189, 0.8321, 0.2788, 0.4326]],

        [[0.1062, 0.2419, 0.3641, 0.9233],
         [0.8551, 0.8739, 0.6573, 0.8063],
         [0.8426, 0.2101, 0.5946, 0.4708],
         [0.7164, 0.2004, 0.5117, 0.9060],
         [0.2189, 0.8321, 0.2788, 0.4326]],

        [[0.1062, 0.2419, 0.3641, 0.9233],
         [0.8551, 0.8739, 0.6573, 0.8063],
         [0.8426, 0.2101, 0.5946, 0.4708],
         [0.7164, 0.2004, 0.5117, 0.9060],
         [0.2189, 0.8321, 0.2788, 0.4326]]])