# Pytorch Basics

In [1]:
import torch
import numpy as np

## Tensors

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print(f"Values: \n{x}\n")

In [3]:
x = torch.ones((4,3,2)) # Tensors of dimension 4x3x2
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([4, 3, 2])
Values: 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])



In [4]:
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.0000e+00, -1.5846e+29,  0.0000e+00],
        [-1.5846e+29,  8.4078e-45,  0.0000e+00]])



In [5]:
describe(torch.rand(2,3)) # uniform distribution
describe(torch.randn(2,3)) # normal distribution

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.7816, 0.7783, 0.4645],
        [0.7026, 0.2630, 0.4895]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1420, 1.0318, 1.3652],
        [1.3672, 0.8773, 0.4699]])



In [6]:
describe(torch.zeros((2,3))) # zeros tensor
x = torch.ones(2 ,3) # ones tensor
describe(x)
x.fill_(5) # all the function with (_) refers to an in-place operation
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])



In [7]:
x = torch.Tensor([[1, 2, 3],
                 [4, 5, 6]]) # creating a tensor from a list
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [8]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy)) # from numpy to pytorch

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9417, 0.9779, 0.4828],
        [0.6808, 0.0164, 0.6307]], dtype=torch.float64)



In [9]:
x = torch.rand(2, 3)
describe(x)
x = x.numpy()
print(f"type: {x.dtype}")
print(f"shape: {x.shape}")
print("numpy value: \n{}\n".format(x))


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.0818, 0.3621, 0.4678],
        [0.6683, 0.0464, 0.3452]])

type: float32
shape: (2, 3)
numpy value: 
[[0.08176452 0.36207968 0.4678439 ]
 [0.6683351  0.04643339 0.34519893]]



## Tensor Types and Size

In [10]:
x = torch.FloatTensor([[1,2,3],
                      [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [11]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [12]:
x = torch.tensor([[1,2,3],
                 [4,5,6]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [13]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [14]:
x.shape, x.size(), x.numel()

(torch.Size([2, 3]), torch.Size([2, 3]), 6)

## Tensor Operations

In [15]:
x = torch.rand(2,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.4979, 0.6069, 0.9216],
        [0.1131, 0.2259, 0.2637]])



In [16]:
describe(x.add(x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9959, 1.2138, 1.8433],
        [0.2262, 0.4518, 0.5274]])



In [17]:
describe(x+x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9959, 1.2138, 1.8433],
        [0.2262, 0.4518, 0.5274]])



In [18]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])



In [19]:
x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [20]:
x = x.reshape(-1)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])



In [21]:
x = x.view(3, -1)
print(f"original: \n{x}\n")
describe(x.sum(dim=0))

original: 
tensor([[0, 1],
        [2, 3],
        [4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([6, 9])



In [22]:
print(f"original: \n{x}\n")
describe(x.sum(dim=1))

original: 
tensor([[0, 1],
        [2, 3],
        [4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([1, 5, 9])



In [23]:
describe(x.T)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 2, 4],
        [1, 3, 5]])



## Indexing, Slicing and Joining

In [24]:
x = torch.arange(6).view(2, -1)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [25]:
describe(x[:1, :2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])



In [26]:
describe(x[0,1])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1



In [27]:
indices = torch.LongTensor([0, 2])
describe(x.index_select(dim=1, index=indices)) # Getting index 0 and 2 along dim=1

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])



In [28]:
indices = torch.LongTensor([0, 0])
describe(x.index_select(dim=0, index=indices)) # Getting index 0 and 0 along dim=1

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])



In [32]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices]) # Get [0, 1] and [0, 1] (0,0) and (1,1) indices

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])



In [33]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [34]:
describe(torch.cat([x, x], dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])



In [35]:
describe(torch.cat([x, x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])



In [36]:
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])



## Linear Algebra Operators

In [104]:
x1 = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [105]:
x2 = torch.ones(3, 2).long()
x2[:, 1] += 1
describe(x2)

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1, 2],
        [1, 2],
        [1, 2]])



In [106]:
describe(x1.mm(x2))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3,  6],
        [12, 24]])



## Tensors and Computational Graphs

In [40]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print("Grad of x: \n{}".format(x.grad))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

Grad of x: 
None


In [41]:
y = (x + 2) * (x + 5) + 3
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)



In [42]:
z = y.mean()
describe(z)
z.backward()
print("Grad of x: \n{}".format(x.grad))

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0

Grad of x: 
tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])


## GPU

In [43]:
print(torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

False
cpu


# Exercises

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0

In [47]:
x = torch.randn(2,4)
x = x.unsqueeze(0)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([1, 2, 4])
Values: 
tensor([[[ 1.4343,  0.9404, -0.1947,  0.7715],
         [-2.0913,  1.8895, -0.3645, -1.0036]]])



2. Remove the dimension you just added to the previous tensor

In [48]:
x = x.squeeze(0)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values: 
tensor([[ 1.4343,  0.9404, -0.1947,  0.7715],
        [-2.0913,  1.8895, -0.3645, -1.0036]])



3. Create a random tensor of shape 5x3 in the interval [3, 7)

In [49]:
x = torch.randint(3, 7, (5, 3)) # this just takes integer random numbers
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[4, 4, 4],
        [6, 5, 3],
        [6, 6, 3],
        [6, 6, 4],
        [6, 6, 5]])



In [50]:
x = 3 + torch.rand(5, 3) * (7 - 3) # random numbers between 3 and 5 float numbers
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[6.1329, 6.3811, 6.4535],
        [6.0007, 3.5024, 3.2082],
        [6.6779, 5.8760, 4.1907],
        [4.5485, 4.2260, 3.6375],
        [5.1668, 6.3698, 3.3702]])



4. Create a tensor with values from a normal distribution 

In [51]:
x = torch.randn((10, ))
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([10])
Values: 
tensor([ 0.0601, -0.8715, -0.9560, -0.8996,  1.4386, -1.0834, -1.7265,  1.3176,
         1.0190, -0.3288])



In [148]:
x = torch.empty(3, 3)
x.normal_()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[-1.2391, -1.3204, -0.2052],
        [-0.9322, -0.9425,  0.3853],
        [ 1.5830, -0.3353, -2.1995]])



5. Retrieve the indexes of all the nonzero elements in the tensor

In [52]:
x = torch.Tensor([1, 1, 1, 0, 3])
x[x.nonzero(as_tuple=True)], x.nonzero(as_tuple=True)

(tensor([1., 1., 1., 3.]), (tensor([0, 1, 2, 4]),))

In [171]:
x[x.nonzero(as_tuple=False)], x.nonzero(as_tuple=False)

(tensor([[1.],
         [1.],
         [1.],
         [3.]]),
 tensor([[0],
         [1],
         [2],
         [4]]))

6. Create a random tensor of size (3,1) and then horizontally stack four copies together.

In [60]:
x = torch.rand(3,1)
describe(x)
describe(torch.cat([x, x, x, x], dim=1))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values: 
tensor([[0.6709],
        [0.0631],
        [0.4468]])

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[0.6709, 0.6709, 0.6709, 0.6709],
        [0.0631, 0.0631, 0.0631, 0.0631],
        [0.4468, 0.4468, 0.4468, 0.4468]])



7. Return the batch matrix-matrix product of two three dimensional matrices

In [74]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
describe(a.bmm(b))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.2670, 1.3095, 1.1905, 1.0152],
         [2.0174, 1.9442, 2.0374, 1.5173],
         [1.9653, 1.8345, 1.6428, 1.8297],
         [1.3138, 1.3741, 1.1070, 1.0458]],

        [[1.6452, 1.4882, 1.1955, 1.3679],
         [1.7729, 1.5241, 1.3460, 1.4522],
         [1.7977, 1.0886, 1.3400, 1.5551],
         [1.6864, 1.6575, 1.3938, 1.4687]],

        [[1.3900, 1.7395, 1.6995, 2.2518],
         [0.7008, 0.9303, 1.1934, 0.9929],
         [0.7654, 0.7833, 1.2646, 1.5072],
         [1.1447, 1.4074, 1.1922, 1.8310]]])



8. Return the batch matrix-matrix product of a 3D matrix and a 2D matrix

In [91]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
a.bmm(b.unsqueeze(0).expand(a.shape[0], *b.size()))

tensor([[[0.2523, 0.8131, 0.9475, 0.6210],
         [0.4607, 1.5885, 1.5654, 1.4585],
         [0.4874, 1.5208, 1.1110, 1.2077],
         [0.5710, 0.5515, 0.6119, 0.6134]],

        [[0.4626, 0.9888, 1.2367, 0.8878],
         [0.8399, 1.3842, 0.9828, 1.2183],
         [0.7616, 0.9095, 1.1669, 0.9320],
         [0.6293, 0.8666, 0.8463, 0.7579]],

        [[0.5896, 1.1626, 0.9370, 0.8243],
         [0.5601, 1.2220, 1.0669, 1.3211],
         [0.4076, 1.3885, 1.3246, 1.3879],
         [0.4910, 1.1813, 1.3293, 1.0785]]])

In [92]:
b.unsqueeze(0).expand(a.shape[0], *b.shape) # Repeat matrix to the same batch of a in order to do 
                                            # batch multiplication matrix

tensor([[[0.4953, 0.0306, 0.0454, 0.1287],
         [0.1700, 0.5925, 0.3597, 0.2035],
         [0.0426, 0.0674, 0.8916, 0.4125],
         [0.2396, 0.6362, 0.4970, 0.3494],
         [0.1359, 0.7506, 0.4321, 0.9424]],

        [[0.4953, 0.0306, 0.0454, 0.1287],
         [0.1700, 0.5925, 0.3597, 0.2035],
         [0.0426, 0.0674, 0.8916, 0.4125],
         [0.2396, 0.6362, 0.4970, 0.3494],
         [0.1359, 0.7506, 0.4321, 0.9424]],

        [[0.4953, 0.0306, 0.0454, 0.1287],
         [0.1700, 0.5925, 0.3597, 0.2035],
         [0.0426, 0.0674, 0.8916, 0.4125],
         [0.2396, 0.6362, 0.4970, 0.3494],
         [0.1359, 0.7506, 0.4321, 0.9424]]])